### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.ec2metadata#5]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by mrchypark** [comment]
@leeper What's a reason not being maintained this project?

**Comment by leeper** [comment]
I am no longer able to do so.

**Comment by jon-mago** [comment]
Hi @leeper, I would be willing to maintain this project.  I'm sorry to hear you're no longer able to do so, but thank you for writing all of these in the first place.

**Comment by jon-mago** [comment]
Closing this, now I've merged
