### ISSUE TITLE
is_ec2 / get_instance_metadata results in 10 second delay on mac

### ISSUE THREAD

**Issue by micwalk** [cloudyr/aws.ec2metadata#7]
I was tracking down why the `aws.s3` library was slow to make an initial request, but quick to perform subsequent requests. I traced the delay back to this psuedo call stack:

```
aws.s3::head_object
aws.s3::s3HTTP
aws.signature:::locate_credentials
ec2metadata:::is_ec2
aws.ec2metadata:::get_instance_metadata
curl::curl_fetch_memory("http://169.254.169.254")
```
Running the curl call directly on a mac produces:
```
> curl::curl_fetch_memory("http://169.254.169.254")
Error in curl::curl_fetch_memory("http://169.254.169.254") : 
  Timeout was reached: Connection timed out after 10001 milliseconds
```

Since when NOT on ec2 it can't connect to the IP, it times out with a default timeout of 10 seconds.  It seems the curl library must be caching the "host unavailable" message for approximately 15 seconds on my system, but I can't find a parameter to control this.

**Is it expected that the `is_ec2` function produces a 10 second delay when not running on ec2**

As a hacky workaround on my system, I just override the is_ec2 function after loading the library, but this obviously won't work as an improvement to this package.:
```
assignInNamespace("is_ec2", function ( ...) { FALSE }, "aws.ec2metadata") 
```

Potential solutions that this package could implement:
- Manually cache the result of is_ec2 or get_instance_metadata. This will produce a 10 second delay only once, instead of every call to this function. This would especially be useful for a "no" result.
- Manually lower the timeout on curl to a lower value
- Perform some faster check to see if the ip / base url is listening on port 80, rather than relying on a timeout at all.

**Comment by joshua-morten** [comment]
I found that adding a timeout works nicely. Maybe this can get wrapped into an update sometime.

`curl::curl_fetch_memory("http://169.254.169.254", handle = curl::new_handle(timeout_ms = 4))`

**Comment by joshua-morten** [comment]
I have an open pull request that adds the timeout to curl.

**Comment by joshua-morten** [comment]
This issue only affects those who are developing aws.ec2metadata and have a copy of the package on their non-ec2 dev box.

**Comment by jon-mago** [comment]
@micwalk Thanks for reporting this, and thanks @jmorten for the initial fix.

I've now changed the timeout to be inline with boto3 for python (1s) and controllable via the same environmental variable (AWS_METADATA_SERVICE_TIMEOUT)

I'd definitely consider a patch which introduced some kind of caching for that check.
